create or replace procedure sp_dropif (t_name IN NVARCHAR2)
as
begin
  EXECUTE IMMEDIATE 'DROP TABLE ' || t_name || ' CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
end;
/
exec sp_dropif('HSBA');
exec sp_dropif('HSBA_DV');
exec sp_dropif('BENHNHAN');
exec sp_dropif('CSYT');
exec sp_dropif('NHANVIEN');
exec sp_dropif('THONGBAO');
/

CREATE TABLE HSBA(
    MAHSBA      NUMBER NOT NULL,
    MABN        NUMBER,
    NGAY        DATE,
    CHANDOAN    NVARCHAR2(100) ENCRYPT,
    MABS        NUMBER,
    MAKHOA      NUMBER,
    MACSYT      NUMBER,
    KETLUAN     NVARCHAR2(100) ENCRYPT,
    
    PRIMARY KEY(MAHSBA)
);

CREATE TABLE HSBA_DV(
    MAHSBA      NUMBER NOT NULL,
    MADV        Number Not Null,
    NGAY        DATE NOT NULL,
    MAKTV       NUMBER,
    KETQUA      NVARCHAR2(100) ENCRYPT
);

CREATE TABLE BENHNHAN(
    MABN        NUMBER NOT NULL,
    MACSYT      NUMBER,
    TENBN       NVARCHAR2(25),
    CMND        NVARCHAR2(10),
    NGAYSINH    DATE,
    SONHA       NUMBER,
    TENDUONG    NVARCHAR2(25),
    QUANHUYEN   NVARCHAR2(25),
    TINHTP      NVARCHAR2(20),
    TIENSUBENH  NVARCHAR2(100),
    TIENSUBENHGD NVARCHAR2(200),
    DIUNGTHUOC  NVARCHAR2(200),
    
    PRIMARY KEY(MABN)
);

CREATE TABLE CSYT(
    MACSYT      NUMBER NOT NULL,
    TENCSYT     NVARCHAR2(25),
    DCCSYT      NVARCHAR2(50),
    SDTCSYT     NVARCHAR2(10),
    TUYENDT     NVARCHAR2(30),
    VUNG        NVARCHAR2(20),
    
    PRIMARY KEY (MACSYT)
);

CREATE TABLE NHANVIEN(
    MANV        NUMBER NOT NULL,
    HOTEN       NVARCHAR2(25),
    PHAI        NVARCHAR2(5),
    NGAYSINH    DATE,
    CMND        NVARCHAR2(10),
    QUEQUAN     NVARCHAR2(20),
    SODT        NVARCHAR2(10),
    CSYT        NUMBER,
    VAITRO      NVARCHAR2(15),
    CHUYENKHOA  NUMBER,
    CAPBAC      NVARCHAR2(15),
    
    PRIMARY KEY(MANV)
);

CREATE TABLE THONGBAO(
    MANV        NUMBER NOT NULL,
    NOIDUNG     NVARCHAR2(1000) ENCRYPT,
    NGAYGIO     DATE,
    DIADIEM     NVARCHAR2(100)
);

-- Thêm khóa ngoại vào các bảng
ALTER TABLE HSBA
ADD CONSTRAINT FK_MABS_MANV FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV);

ALTER TABLE HSBA
ADD CONSTRAINT FK_MABN_MABN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBA_HSBA FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA);

ALTER TABLE HSBA_DV
ADD CONSTRAINT PK_MAHS_MADV_NGAY PRIMARY KEY(MAHSBA, MADV, NGAY);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_MAKTV_MANV FOREIGN KEY (MAKTV) REFERENCES NHANVIEN(MANV);

ALTER TABLE BENHNHAN
ADD CONSTRAINT FK_MACSYT_MACSYT FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT);

ALTER TABLE CSYT
ADD CONSTRAINT CHECK_TUYENDT CHECK (TUYENDT IN (N'Điều trị ngoại trú', N'Điều trị nội trú', N'Điều trị chuyên sâu'));

ALTER TABLE CSYT
ADD CONSTRAINT CHECK_VUNG CHECK (VUNG IN (N'Trung tâm', N'Cận trung tâm', N'Ngoại thành'));

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_CSYT_MACSYT FOREIGN KEY (CSYT) REFERENCES CSYT(MACSYT);

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_VAITRO CHECK (VAITRO IN (N'Y sĩ/bác sĩ', N'Nghiên cứu',N'Thanh tra', N'Cơ sở y tế'));

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_CAPBAC CHECK (CAPBAC IN (N'Giám đốc sở', N'Giám đốc cơ sở y tế', N'Y/Bác sĩ'));

ALTER TABLE THONGBAO
ADD CONSTRAINT FK_THONGBAO_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

--
INSERT INTO CSYT(MACSYT, TENCSYT, DCCSYT, SDTCSYT, TUYENDT, VUNG)
    VALUES (927262622, 'Trung tâm An Bình', '90 Mạc Đĩnh Chi, Hà Nội', '0927165821', 'Điều trị chuyên sâu', 'Trung tâm');
--

INSERT INTO BENHNHAN(MABN, MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC)
    VALUES (82719202, 927262622, N'Huỳnh Thúc Hoa', '3419258828', TO_DATE('03/09/1992', 'dd/mm/yyyy'), 25, N'Mãn Nghi', N'Quận 8', N'TP Hồ Chí Minh', N'Không', N'Viêm phổi', N'Không');
    
--
INSERT INTO HSBA(MAHSBA, MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN)
    VALUES(900129582, 82719202, TO_DATE('21/09/2020', 'dd/mm/yyyy'), 'Có khối u lành tính tại thực quản', 100001, 9282155, 92762622, 'Phẫu thuật');

--
INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, CAPBAC)
    VALUES (100001, N'Huỳnh Văn Phong', 'Nam', TO_DATE('01/09/1990', 'dd/mm/yyyy'), '3411745902', N'Cao Bằng', '0765268987', 927262622, 'Thanh tra', 9282155, 'Giám đốc sở');

INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, CAPBAC)
    VALUES (100002, N'Lê Văn Mẫn', 'Nam', TO_DATE('21/02/1991', 'dd/mm/yyyy'), '3911523982', N'Đà Nẵng', '0234255512', 927262622, 'Nghiên cứu', 9282155, 'Y/Bác sĩ');

INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, CAPBAC)
    VALUES (100003, N'Nguyễn Thị Lê', 'Nữ', TO_DATE('11/04/1989', 'dd/mm/yyyy'), '3289123577', N'Đồng Tháp', '0247881235', 927262622, 'Cơ sở y tế', 9282155, 'Y/Bác sĩ');

--
INSERT INTO THONGBAO(MANV, NOIDUNG, NGAYGIO, DIADIEM) 
    VALUES (100001, 'Hôm nay là Chủ Nhật', sysdate, 'Hồ Chí Minh');
    
INSERT INTO THONGBAO(MANV, NOIDUNG, NGAYGIO, DIADIEM) 
    VALUES (100001, 'Hôm nay là Thứ Hai, thứ Hai có thưởng', sysdate, 'Hồ Chí Minh');  
--
    
Alter Session Set "_ORACLE_SCRIPT"=false;