create or replace procedure sp_dropif (t_name IN NVARCHAR2)
as
begin
  EXECUTE IMMEDIATE 'DROP TABLE ' || t_name || ' CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
end;
/
exec sp_dropif('HSBA');
exec sp_dropif('HSBA_DV');
exec sp_dropif('BENHNHAN');
exec sp_dropif('CSYT');
exec sp_dropif('NHANVIEN');
/

CREATE TABLE HSBA(
    MAHSBA      NUMBER NOT NULL,
    MABN        NUMBER,
    NGAY        DATE,
    CHANDOAN    NVARCHAR2(100),
    MABS        NUMBER,
    MAKHOA      NUMBER,
    MACSYT      NUMBER,
    KETLUAN     NVARCHAR2(100),
    
    PRIMARY KEY(MAHSBA)
);

CREATE TABLE HSBA_DV(
    MAHSBA      NUMBER NOT NULL,
    MADV        Number Not Null,
    NGAY        DATE NOT NULL,
    MAKTV       NUMBER,
    KETQUA      NVARCHAR2(100)
);

CREATE TABLE BENHNHAN(
    MABN        NUMBER NOT NULL,
    MACSYT      NUMBER,
    TENBN       NVARCHAR2(25),
    CMND        NVARCHAR2(10),
    NGAYSINH    DATE,
    SONHA       NUMBER,
    TENDUONG    NVARCHAR2(25),
    QUANHUYEN   NVARCHAR2(25),
    TINHTP      NVARCHAR2(20),
    TIENSUBENH  NVARCHAR2(100),
    TIENSUBENHGD NVARCHAR2(200),
    DIUNGTHUOC  NVARCHAR2(200),
    
    PRIMARY KEY(MABN)
);

CREATE TABLE CSYT(
    MACSYT      NUMBER NOT NULL,
    TENCSYT     NVARCHAR2(25),
    DCCSYT      NVARCHAR2(50),
    SDTCSYT     NVARCHAR2(10),
    
    PRIMARY KEY (MACSYT)
);

CREATE TABLE NHANVIEN(
    MANV        NUMBER NOT NULL,
    HOTEN       NVARCHAR2(25),
    PHAI        NVARCHAR2(5),
    NGAYSINH    DATE,
    CMND        NVARCHAR2(10),
    QUEQUAN     NVARCHAR2(20),
    SODT        NVARCHAR2(10),
    CSYT        NUMBER,
    VAITRO      NVARCHAR2(15),
    CHUYENKHOA  NVARCHAR2(15),
    
    PRIMARY KEY(MANV)
);

CREATE TABLE THONGBAO(
    NOIDUNG     NVARCHAR2(1000),
    NGAYGIO     DATE,
    DIADIEM     NVARCHAR2(100)
);

-- Thêm khóa ngoại vào các bảng
ALTER TABLE HSBA
ADD CONSTRAINT FK_MABS_MANV FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV);

ALTER TABLE HSBA
ADD CONSTRAINT FK_MABN_MABN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBA_HSBA FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA);

ALTER TABLE HSBA_DV
ADD CONSTRAINT PK_MAHS_MADV_NGAY PRIMARY KEY(MAHSBA, MADV, NGAY);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_MAKTV_MANV FOREIGN KEY (MAKTV) REFERENCES NHANVIEN(MANV);

ALTER TABLE BENHNHAN
ADD CONSTRAINT FK_MACSYT_MACSYT FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_CSYT_MACSYT FOREIGN KEY (CSYT) REFERENCES CSYT(MACSYT);

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_VAITRO CHECK (VAITRO IN (N'Y sĩ/bác sĩ', N'Nghiên cứu',N'Thanh tra', N'Cơ sở y tế'));

Alter Session Set "_ORACLE_SCRIPT"=false;

-- Thêm các nhân viên là Thanh tra vào
INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA)
    VALUES (100001, 'Lương Bằng Hải', 'Nam', TO_DATE('21/02/1988', 'dd/mm/yyyy'), '3492791822', 'Đồng Tháp', '0917265827', 'Thanh tra', 'Điều dưỡng');
INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA)
    VALUES (100002, 'Cao Mỹ Duyên', 'Nữ', TO_DATE('13/05/1992', 'dd/mm/yyyy'), '3195228792', 'Đồng Nai', '0117355789', 'Thanh tra', 'Phụ sản');
INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA)
    VALUES (100001, 'Lâm Nhật Tân', 'Nam', TO_DATE('09/02/1980', 'dd/mm/yyyy'), '3551783240', 'Sơn La', '0385265147', 'Thanh tra', 'Khoa nội');
INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA)
    VALUES (100001, 'Ý Mỹ Tài', 'Nam', TO_DATE('24/01/1989', 'dd/mm/yyyy'), '3532724889', 'Bình Dương', '0912455009', 'Thanh tra', 'Khoa ngoại');
INSERT INTO NHANVIEN(MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA)
    VALUES (100001, 'Huỳnh Văn Phong', 'Nam', TO_DATE('01/09/1990', 'dd/mm/yyyy'), '3411745902', 'Cao Bằng', '0765268987', 'Thanh tra', 'Hồi sức');