/*
    users.sql
    --------------
    Tạo role và user. Phân quyền cho user
*/

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Cấp bậc nhân viên
CREATE ROLE GIAMDOCSO;
CREATE ROLE GIAMDOCSOYTE;

-- Vai trò nhân viên
CREATE ROLE BENHNHAN;
CREATE ROLE THANHTRA;
CREATE ROLE COSOYTE;
CREATE ROLE YBACSI;
CREATE ROLE NGHIENCUU;
CREATE ROLE NHANVIEN;

-- Tạo user
CREATE USER "900001" IDENTIFIED BY "lbcphat123";
CREATE USER "900002" IDENTIFIED BY "nhkhoi123";
CREATE USER "900003" IDENTIFIED BY "nsbao123";
CREATE USER "900004" IDENTIFIED BY "pstung123";

-- Phân quyền cho user
GRANT DBA TO "900001";
GRANT DBA TO "900002";
GRANT DBA TO "900003";
GRANT DBA TO "900004";